const mongoose = require("mongoose");

const manufacturerSchema = new mongoose.Schema({
  name: { type: String, required: true },
  brand: [
    {
      type: String,
      required: true,
    },
  ],
  dateCreated: {
    type: String, //autogenerated
  },
});

const Manufacturer = mongoose.model("Manufacturer", manufacturerSchema);

module.exports = Manufacturer;
